[tool.poetry]
name = "angel_system"
version = "0.1.0"
description = ""
authors = ["Kitware, Inc. <kitware@kitware.com>"]

[tool.poetry.dependencies]
python = "^3.8.10,<3.11"
matplotlib = "^3.5.1"
numpy = "^1.22.2"
Pillow = "^8"
simpleaudio = "^1.0.4"
# TODO: pin a version AFTER 0.18
smqtk-detection = {git = "https://github.com/purg/SMQTK-Detection", rev = "dev/unlock-py-req"}
torch = "^1.11.0"
torchvision = "^0.12.0"
trimesh = {extras = ["easy"], version = "^3.10.2"}
pytorchvideo = "^0.1.5"
transitions = "^0.8.11"

[tool.poetry.dev-dependencies]
ipython = "^8.0.1"

[build-system]
requires = ["poetry-core==1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."smqtk_plugins"]
# Activity detector
"angel_system.impls.detect_activities.pytorchvideo_slow_fast_r50" = "angel_system.impls.detect_activities.pytorchvideo_slow_fast_r50"
